In [29]:
from sklearn import svm
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize

In [20]:
Xtrain = np.array(pd.read_csv('csv/x_train.csv', sep=','))
ytrain = np.array(pd.read_csv('csv/y_train.csv', sep=',', header=None))
Xtest = np.array(pd.read_csv('csv/x_test.csv', sep=','))
ytest = np.array(pd.read_csv('csv/y_test.csv', sep=',', header=None))

In [21]:
clf = svm.SVC(C = 0.5, kernel='linear')
clf.fit(Xtrain, np.ravel(ytrain))

p = clf.predict(Xtest)

In [10]:
clf.coef_[0]

array([ -5.12952179e-02,  -1.90605782e+00,   4.07787064e-02,
         8.15115877e-01,  -1.31285138e+00,  -5.25833262e-02,
        -8.66411095e-01,  -5.93206445e-01,   6.03430857e-02,
         6.73649361e-01,  -1.82406650e+00,   2.48463308e-01,
         1.24178126e+00,   4.08291702e-01,   1.65007297e+00,
         3.15841569e-01,   3.44068603e+00,   1.38166532e+00,
        -1.70579578e+00,  -8.83413810e-01,   1.38617480e+00,
         2.28343964e-01,   2.41791670e-01,  -5.88762806e-03,
        -1.25822467e+00,   8.88041026e-01,   9.84926424e-03,
         1.48656863e+00,  -6.46249358e-01,  -4.30911038e-03,
        -1.16145380e-01,   3.35926564e-01,   5.18876143e-02,
        -6.93268299e-01,   4.71128709e-01,  -2.22139595e-01,
         4.51224495e-01,   1.67721593e+00,   2.97386052e-01,
         3.18102703e-01,   1.76964168e-01,  -9.17682116e-01,
        -9.21958068e-02,   1.05061113e+00,  -5.09193424e-02,
         9.08538480e-01,  -1.19058426e-02,   8.01913415e-02,
        -1.00073429e+00,

In [18]:
np.sum(p == np.ravel(ytest)) / (len(p) + 0.0)

0.60162601626016265

In [23]:
c = clf.decision_function(Xtest)

In [26]:
min(c), max(c)

(-1322.1715176025396, 1362.0444226941104)

In [27]:
c[:100]

array([-577.80823409,  548.09421433,   -7.64651155, -131.45643424,
       -628.24025326,  706.68184639, -758.88572388,  783.76167054,
       -200.32305276,  129.39330179,  283.31770147, -427.14302408,
       -699.64101022,  485.45339979,  -11.28642671,   50.76416165,
       -343.16853272,  206.73836894, -469.00712966,  331.05701173,
       -600.08485358,  508.76553334,  464.48452688, -482.1279087 ,
        272.97755516, -350.72706287,  -54.08435958,  -75.9407612 ,
       -371.6994596 ,  278.98916281,  420.69985319, -418.02956694,
       -301.21905696,  209.8191343 ,  265.45514257, -341.89371102,
       -230.55525254,   -8.38151699,  569.45399196, -633.8361057 ,
       -693.91877352,  667.44978274,  -54.42471313,  -91.57573908,
       -431.16506951,  294.85312594, -422.64603632,  411.66800732,
        182.39588983, -326.38180756,  250.02534504, -277.39952408,
         37.43114955,  -62.59947168,  109.06221152, -220.67365127,
        694.72631533, -673.86062013,    0.89066655, -136.16054

In [28]:
p[:100]

array([ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,
        0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,
        0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,
        0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.])

In [70]:
probs = (np.ones(c.shape) / (1+np.exp(-50 * (c / np.linalg.norm(c)))))
final_probs = [probs[i] / (probs[i] + probs[i+1]) for i in xrange(len(probs) / 2)]
probs

array([ 0.22370858,  0.76498396,  0.49588382, ...,  0.7409548 ,
        0.49897062,  0.50197765])

In [71]:
import pred_to_record
pred_to_record.pred_to_record(probs)

{'Atlanta Hawks': [50.442128057389873, 31.557871942610127],
 'Boston Celtics': [43.498215037789379, 38.501784962210621],
 'Brooklyn Nets': [47.341723144116152, 34.658276855883841],
 'Charlotte Hornets': [24.494602964608841, 57.505397035391155],
 'Chicago Bulls': [42.552387985305508, 39.447612014694499],
 'Cleveland Cavaliers': [48.652112871270788, 33.347887128729198],
 'Dallas Mavericks': [45.5349339093042, 36.465066090695792],
 'Denver Nuggets': [27.147036347591133, 54.852963652408882],
 'Detroit Pistons': [28.286228038536343, 53.713771961463671],
 'Golden State Warriors': [62.942485282102439, 19.057514717897551],
 'Houston Rockets': [47.543337584129532, 34.456662415870461],
 'Indiana Pacers': [40.906242370251832, 41.093757629748175],
 'Los Angeles Clippers': [46.218842483040255, 35.781157516959745],
 'Los Angeles Lakers': [15.397669905031002, 66.602330094969005],
 'Memphis Grizzlies': [54.058352440808598, 27.941647559191413],
 'Miami Heat': [36.689405755137187, 45.310594244862813],
 

In [72]:
pred_to_record.rms_round(probs)

10.853570840972107

In [73]:
Xtrain = np.array(pd.read_csv('csv/x_train_significant.csv', sep=','))
ytrain = np.array(pd.read_csv('csv/y_train.csv', sep=',', header=None))
Xtest = np.array(pd.read_csv('csv/x_test_significant.csv', sep=','))
ytest = np.array(pd.read_csv('csv/y_test.csv', sep=',', header=None))

In [74]:
clf = svm.SVC(C = 0.5, kernel='linear')
clf.fit(Xtrain, np.ravel(ytrain))

p = clf.predict(Xtest)

In [75]:
c = clf.decision_function(Xtest)
probs = (np.ones(c.shape) / (1+np.exp(-50 * (c / np.linalg.norm(c)))))
pred_to_record.rms_round(probs)

10.437113266288401

In [76]:
pred_to_record.pred_to_record(probs)

{'Atlanta Hawks': [51.138562063385152, 30.861437936614823],
 'Boston Celtics': [45.450190156510757, 36.549809843489228],
 'Brooklyn Nets': [42.710915205236134, 39.289084794763866],
 'Charlotte Hornets': [24.668755101672311, 57.331244898327682],
 'Chicago Bulls': [51.442610142229299, 30.557389857770715],
 'Cleveland Cavaliers': [52.699063163660526, 29.300936836339446],
 'Dallas Mavericks': [41.573160489280653, 40.426839510719354],
 'Denver Nuggets': [26.137219621166487, 55.86278037883352],
 'Detroit Pistons': [27.03110027487978, 54.968899725120217],
 'Golden State Warriors': [59.986213738913015, 22.013786261086963],
 'Houston Rockets': [45.443458815391615, 36.556541184608399],
 'Indiana Pacers': [44.827386274195199, 37.172613725804801],
 'Los Angeles Clippers': [48.443255923995103, 33.55674407600489],
 'Los Angeles Lakers': [18.930150123433922, 63.069849876566082],
 'Memphis Grizzlies': [51.159900953176191, 30.840099046823802],
 'Miami Heat': [35.176087233224862, 46.823912766775152],
 '